In [14]:
## sk-learn常见的机器学习框架
#导包 导入线性回归的模型
%matplotlib notebook
from sklearn.linear_model import LinearRegression
import numpy as np
#实例化模型
model = LinearRegression()

In [15]:
#准备数据
feature=np.array([80,95,104,112,125,135])
label=np.array([200,230,245,247,259,262])

In [16]:
#模型训练
model.fit(feature.reshape(-1,1),label)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
model.coef_ #斜率

array([ 1.08593555])

In [18]:
model.intercept_ #截距

122.67599300524607

## 预测

In [19]:
model.predict(np.array([[80]]))

array([ 209.55083687])

In [20]:
model.predict(np.array([[90]]))

array([ 220.41019236])