# 机器学习的几个关键步骤
梯度下降算法实现 （一次梯度下降，更新一次m和b）  
训练达到梯度最低点 （多次的更新m和b，直到达到最低点）  
测试训练结果准确性 （用测试集的数据，来测试m和b预测的准确性）  
进行新的预测 （来进行新的预测）  

## numpy矩阵的乘法

In [12]:
import numpy as np
data = np.array([
    [80,200],
    [95,230],
    [104,245],
    [112,247],
    [125,259],
     [135,262]
])

## 数组的拆分

In [13]:
feature=data[:,0:1]
feature

array([[ 80],
       [ 95],
       [104],
       [112],
       [125],
       [135]])

In [14]:
label=data[:,1:2]
label

array([[200],
       [230],
       [245],
       [247],
       [259],
       [262]])

In [16]:
# 思考：怎么把初等数学的运算，改为矩阵乘法？两个矩阵如何相乘
# y=mx+b
np.ones((len(feature),1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [18]:
# 矩阵的拼装
Feature=np.hstack((feature,np.ones((len(feature),1))))
Feature

array([[  80.,    1.],
       [  95.,    1.],
       [ 104.,    1.],
       [ 112.,    1.],
       [ 125.,    1.],
       [ 135.,    1.]])

In [20]:
Weight=np.ones((2,1))
Weight

array([[ 1.],
       [ 1.]])

In [21]:
#矩阵相乘的结果就是面积的预测
#y=mx+b
#预测的房价
np.dot(Feature,Weight)

array([[  81.],
       [  96.],
       [ 105.],
       [ 113.],
       [ 126.],
       [ 136.]])

In [22]:
#预测的房价 - 真实的房价 得到差价
np.dot(Feature,Weight)-label

array([[-119.],
       [-134.],
       [-140.],
       [-134.],
       [-133.],
       [-126.]])

In [23]:
#mse最小均方差
mse=np.sum(np.square(np.dot(Feature,Weight)-label))
mse

103238.0

In [26]:
# mse对b的偏导数
# mse对m的偏导数
np.dot(Feature.T,(np.dot(Feature,Weight)-label))

array([[-85453.],
       [  -786.]])

# 用矩阵运算的方式把初等数学的梯度下降重构

# 初等数学的实现

In [31]:
import numpy as np
data = np.array([
    [80,200],
    [95,230],
    [104,245],
    [112,247],
    [125,259],
     [135,262]
])
mhistory = []
bhistory = []
msehistory = []

b = 1
m = 1
learningrate = 0.00002

def gradentdecent():
    global b ,m
    bslop = 0
    mslop = 0
    mse = 0
    for index ,item in enumerate(data[:,1]):
        bslop = bslop + (b - item + data[:,0][index] * m)
        mslop = mslop + (b - item + data[:,0][index] * m)*data[:,0][index]
        mse = mse + (m*data[:,0][index] + b-item)**2
    b = b -bslop*learningrate
    m = m - mslop*learningrate
    return mse

#%%time#看单元格执行时间
i = 0
for i in range(2000000):
    mse = gradentdecent()
    i = i+1
    if(i%100000 == 0):
        print("b={},m={},mse={}".format(b,m,mse))

SyntaxError: invalid syntax (<ipython-input-31-cc529e66bb32>, line 31)

### 高等数学的方式重构代码

In [38]:
import numpy as np
data = np.array([
    [80,200],
    [95,230],
    [104,245],
    [112,247],
    [125,259],
     [135,262]
])


Weight=np.ones((2,1))#m,b，采用矩阵的方式指定权重
ones=np.ones((len(data),1))
Feature=np.hstack((data[:,0:1],ones))
learningrate = 0.00001
ones

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [33]:
Feature

array([[  80.,    1.],
       [  95.,    1.],
       [ 104.,    1.],
       [ 112.,    1.],
       [ 125.,    1.],
       [ 135.,    1.]])

In [39]:
def gradentdecent2():#采用矩阵的方式梯度下降
    global Weight
    Weight=Weight-learningrate*np.dot(Feature.T,(np.dot(Feature,Weight)-label))
    


In [40]:
%%time
#看单元格执行时间
i = 0
for i in range(1000000):
    gradentdecent2()
    i = i+1
    if(i%100000 == 0):
        print("b={},m={}".format(Weight[0],Weight[1]))

b=[ 2.01021985],m=[ 19.54966858]
b=[ 1.86937935],m=[ 35.26384083]
b=[ 1.74999983],m=[ 48.58352059]
b=[ 1.64881112],m=[ 59.87357558]
b=[ 1.56304132],m=[ 69.44327576]
b=[ 1.49034095],m=[ 77.55476517]
b=[ 1.4287185],m=[ 84.43024289]
b=[ 1.37648596],m=[ 90.25804979]
b=[ 1.3322125],m=[ 95.19782774]
b=[ 1.29468534],m=[ 99.38489273]
Wall time: 5.3 s
