In [9]:
import numpy as np
data=np.loadtxt('cars.csv',delimiter=',',skiprows=1,usecols=(4,5,6,1))
data

array([[ 130.    ,    1.752 ,   12.    ,   18.    ],
       [ 165.    ,    1.8465,   11.5   ,   15.    ],
       [ 150.    ,    1.718 ,   11.    ,   18.    ],
       ..., 
       [  84.    ,    1.1475,   11.6   ,   32.    ],
       [  79.    ,    1.3125,   18.6   ,   28.    ],
       [  82.    ,    1.36  ,   19.4   ,   31.    ]])

In [12]:
feature=data[:,0:3]
ones=np.ones((len(data),1))
Feature=np.hstack((feature,ones))
Feature

array([[ 130.    ,    1.752 ,   12.    ,    1.    ],
       [ 165.    ,    1.8465,   11.5   ,    1.    ],
       [ 150.    ,    1.718 ,   11.    ,    1.    ],
       ..., 
       [  84.    ,    1.1475,   11.6   ,    1.    ],
       [  79.    ,    1.3125,   18.6   ,    1.    ],
       [  82.    ,    1.36  ,   19.4   ,    1.    ]])

In [13]:
label=data[:,-1:]

In [14]:
Weight=np.ones((4,1))#m1,m2,m3,b
Weight

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [21]:

learningrate = 0.1

#记录mse对m和b变化率的惯性
m=np.zeros((4,1))
#记录mse对m和b变化率的速度
v=np.zeros((4,1))

# 记录mse的变化过程
msehistory = []

def gradentdecent():#采用矩阵的方式梯度下降
    global Weight,learningrate,m,v
    #计算MSE
    mse=np.sum(np.square(np.dot(Feature,Weight)-label))
    msehistory.append(mse)
    #计算的是m和b的梯度
    slop=np.dot(Feature.T,(np.dot(Feature,Weight)-label))
    #核心逻辑，Adam    
    beta_1=0.9
    beta_2=0.999
    
    m=beta_1*m+(1-beta_1)*slop
    v=beta_2*v+(1-beta_2)*(slop**2)
    
    m_p=m/(1-beta_1)
    v_p=v/(1-beta_2)
    
    Weight=Weight-learningrate*m_p/np.sqrt(v_p+0.000000001)
    return slop
    
i = 0
for i in range(10000000):
    slop=gradentdecent()
    #print(slop[0][0],slop[1][0],slop[2][0],slop[3][0])
    if np.sum(np.square(slop))<0.5:
        break

In [22]:
slop

array([[-0.14773255],
       [-0.00205862],
       [-0.01983076],
       [-0.00130713]])

In [23]:
#85	1.2935	16 #21
85*Weight[0][0]+1.2935*Weight[1][0]+16*Weight[2][0]+Weight[3][0]

17.3627480284031

In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

feature = np.array([80,95,104,112,125,135])
label = np.array([200,230,245,274,259,262])

model.fit(feature.reshape(-1,1),label.reshape(-1,1))

model.coef_   #斜率

model.intercept_ #截距

model.predict([[80]])  #预测

array([[ 212.70522108]])