In [1]:
import numpy as np
data=np.array([
    [5,0],
    [15,0],
    [25,1],
    [35,1],
    [45,1],
    [55,1],
])

In [2]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [3]:
feature=data[:,0:1]
label=data[:,-1:]
Feature=np.hstack((feature,np.ones((len(data),1))))
Feature

array([[  5.,   1.],
       [ 15.,   1.],
       [ 25.,   1.],
       [ 35.,   1.],
       [ 45.,   1.],
       [ 55.,   1.]])

In [4]:
Weight=np.ones((2,1))
changeweight=np.ones((2,1))
learningrate=0.01
Weight

array([[ 1.],
       [ 1.]])

In [5]:
def grandentDecent():
    global Weight,changeweight,learningrate
    #mse crossentroyError
    mse = np.sum(np.power((sigmoid(np.dot(Feature,Weight))-label),2))
    msehistory.append(mse)
    if len(msehistory)>=2:
        if(msehistory[-1]>msehistory[-2]):
            learningrate = learningrate /2
        else :
            learningrate = learningrate * 1.1
    
    slop=np.dot(Feature.T,(sigmoid(np.dot(Feature,Weight))-label))
    ###关键代码
    changeweight = changeweight + slop**2       
    Weight = Weight - learningrate* slop/np.sqrt(changeweight)

In [6]:
msehistory=[]
mhistory=[]
bhistory=[]
for i in range(10000):
    grandentDecent()
    mhistory.append(Weight[0][0])
    bhistory.append(Weight[1][0])

In [7]:
Weight

array([[  0.85847598],
       [-16.93829089]])

In [8]:
sigmoid(np.dot(np.array([[22,1]]),Weight))

array([[ 0.87524813]])